spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${POSTGRES_USER:inventory_user}
    password: ${POSTGRES_PASSWORD:online13}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 30

management:
  endpoints:
    flyway:
      enabled: true
    web:
      exposure:
        include: info, health, flyway, metrics
server:
  port: 8000
  error:
    include-stacktrace: never

logging:
  level:
    org:
      hibernate:
        SQL_SLOW: INFO